apiVersion: v1
kind: Service
metadata:
  name: redis-service-abbou
spec:
  selector:
    app: redis-abbou
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: redis-service-abbou
spec:
  selector:
    app: redis-abbou
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer


